/**
 * Profile generator: turns rule-based suggestions into actual agent profiles.
 */

import { getArtifacts } from "./data";
import { evaluateRules, type ProfileSuggestion } from "./profile-rules";
import { listProfiles, createProfile } from "@/lib/agents/profiles/registry";
import type { ProfileConfig } from "@/lib/validators/profile";

const MIN_CONFIDENCE = 0.6;

/**
 * Suggest profiles based on artifacts from a scan.
 * Filters out suggestions that match existing profiles.
 */
export function suggestProfiles(scanId: string): ProfileSuggestion[] {
  const artifacts = getArtifacts({ scanId });
  const suggestions = evaluateRules(artifacts);

  // Filter by minimum confidence
  const confident = suggestions.filter((s) => s.confidence >= MIN_CONFIDENCE);

  // Filter out profiles that already exist (by ID match)
  const existing = listProfiles();
  const existingIds = new Set(existing.map((p) => p.id));
  const existingNames = new Set(existing.map((p) => p.name.toLowerCase()));

  return confident.filter(
    (s) => !existingIds.has(s.ruleId) && !existingNames.has(s.name.toLowerCase())
  );
}

/**
 * Generate a ProfileConfig from a suggestion.
 */
export function generateProfileConfig(suggestion: ProfileSuggestion): ProfileConfig {
  return {
    id: `env-${suggestion.ruleId}`,
    name: suggestion.name,
    version: "1.0.0",
    domain: "work",
    tags: suggestion.tags,
    supportedRuntimes: ["claude-code"],
    allowedTools: suggestion.suggestedTools,
    canUseToolPolicy: {
      autoApprove: ["Read", "Grep", "Glob"],
      autoDeny: [],
    },
    maxTurns: 30,
    author: "stagent-env",
    tests: [
      {
        task: `Perform a ${suggestion.name.toLowerCase()} task`,
        expectedKeywords: suggestion.tags.slice(0, 3),
      },
    ],
  };
}

/**
 * Generate a SKILL.md from a suggestion.
 */
export function generateSkillMd(suggestion: ProfileSuggestion): string {
  const lines = [
    "---",
    `name: ${suggestion.name}`,
    `description: ${suggestion.description}`,
    "---",
    "",
    suggestion.systemPrompt,
    "",
    "## Matched Artifacts",
    "",
    ...suggestion.matchedArtifacts.map(
      (a) => `- **${a.name}** (${a.category})`
    ),
    "",
    `> Auto-generated by Stagent environment scanner with ${Math.round(suggestion.confidence * 100)}% confidence.`,
  ];

  return lines.join("\n");
}

/**
 * Create a profile from a suggestion — writes to ~/.claude/skills/ and registers.
 */
export function createProfileFromSuggestion(
  suggestion: ProfileSuggestion,
  overrides?: { name?: string; description?: string; systemPrompt?: string }
): void {
  const config = generateProfileConfig(suggestion);
  let skillMd = generateSkillMd(suggestion);

  // Apply overrides
  if (overrides?.name) config.name = overrides.name;
  if (overrides?.systemPrompt) {
    skillMd = skillMd.replace(suggestion.systemPrompt, overrides.systemPrompt);
  }

  createProfile(config, skillMd);
}
